### ISSUE TITLE
Creating a put call

### ISSUE THREAD

**Issue by spatialgeorge** [geonetwork-delwp/core-geonetwork#10]
Hi Simon,

Hope your well, it’s been a while since we have spoken.

I need another python call to update the Data Classification with either ‘unclassified’ or ‘Classified’.
The classification will be managed in the Raster or vector data platforms and pushed to Geonetwork to update.

Thanks

**Comment by sppigot** [comment]
George - all well here - yes, haven't been able to make the stand ups but should be able to get this and #9 underway shortly.
