### ISSUE TITLE
UUID Issue ?!?!

### ISSUE THREAD

**Issue by spatialgeorge** [geonetwork-delwp/core-geonetwork#13]
Simon,

On of the developers for another application has come back to use with an issue with the UUID's from Geonetwork saying these should have hyphens.

below is email from Slavo...
[UUID.pdf](https://github.com/geonetwork-delwp/core-geonetwork/files/4855778/UUID.pdf)

Just wondering if you have any update regarding the issue with UUID numbers generated in Geonetwork.
I told Jirotech to change validation for UUID without hyphens but I’m getting same validation error from APIs (see attached) which prevents me from publishing. At the moment I’m putting some randomly generated numbers to pass this problem.

Example of Metadata UUID from Geonetwork :

Name : cip04-2018-19_melb-multi-epoch2  
Geonetwork UUID : d7019d218cc5ffb92697a56c2077e17fad0c4590  - which is not valid

What I see from internet the correct format for UUID4 should be like this…   ad4b1b14-2449-42b3-98a7-cf2af426e184

You can use various online tools here is one for example - https://www.beautifyconverter.com/uuid-validator.php

Geonetwork documentation

Here is screenshot from Geonetwork documentation and I can see that expectation is to have valid UUID:
https://geonetwork-opensource.org/manuals/2.10.4/eng/developer/xml_services/metadata_xml_search_retrieve.html

**Comment by sppigot** [comment]
Fixed in both metashare and rastermeta metartools. Now uses uuid v5 - generates a conventional uuid with dashes from the anzlicid for datasets and the projectid from rastermeta projects.
