### ISSUE TITLE
Missing Geonetwork records

### ISSUE THREAD

**Issue by spatialgeorge** [geonetwork-delwp/core-geonetwork#15]
We have discovered missing records in Geonetwork.  Investigated and cannot resolve.   The excel file added is the list of the missing records that exist in MetaShare.

[MetaShare_2020_08_04.xlsx](https://github.com/geonetwork-delwp/core-geonetwork/files/5031929/MetaShare_2020_08_04.xlsx)

**Comment by milleri** [comment]
This is a metar Metashare issue.  The Metashare log shows errors for the missing datasets, of two types:

a. All of the FOREST_ABG_... , BUSHFIRE_SEVERITY_EAST_AND_NORTHEAST_VICTORIA_2019-20, VIC_LANDCOVER_TS, datasets show the following error:

_2020-08-10T21:36:39,968 INFO  [main] - Processing Dataset
        'FOREST_ABG_2012'
        ANZLIC_ID ANZVI0803008595
        UUID: 1682d385-734b-55db-bbf0-4d866972a6d5
2020-08-10T21:36:39,968 ERROR [main] - Problem whilst processing dataset 'FOREST_ABG_2012'Cause: null value for attribute "codeListValue" from object of type au.gov.vic.delwp.Dataset - org.jibx.runtime.JiBXExceptionProcessing of 'FOREST_ABG_2012' aborted_

b. Datasets MICLUP_INDUSTRIAL_AUG2020, FOREST_AABG_1988_TEST_ES, MICLUP_Copy_3, MICLUP_Copy_2, MICLUP_Copy_1, BEACH_EMERGENCY_SIGNS, MICLUP_INDUSTRIAL_JUN2020, MICLUP_COMMERCIAL_FUT_JUN2020, ESTA_MARKER, MICLUP, ESTA_EMERGENCY_MARKERS, SENSITIVITY, EWSP, MOG_SURVEY_GRID, MOG_SURVEY_GRID_CENTROID, MICLUP_COMMERCIAL_EXT_JUN2020, IMMEDIATE_PROTECTION_AREAS

show errors:
_Cause: Untranslated ANZLIC Search Word 'Industrial'
Cause: Untranslated ANZLIC Search Word 'AGB'
Cause: Untranslated ANZLIC Search Word 'MICLUP'
Cause: Untranslated ANZLIC Search Word 'EMERGENCY'
Cause: Untranslated ANZLIC Search Word 'Areas of cultural heritage sensitivity'
Cause: Untranslated ANZLIC Search Word 'Old-growth survey grid centroid'
Cause: Untranslated ANZLIC Search Word 'Old-growth forest'
Cause: Untranslated ANZLIC Search Word 'Commercial'_

**Comment by sppigot** [comment]
Industrial|economy
AGB|environment
MICLUP|economy
EMERGENCY|transportation
Areas of cultural heritage sensitivity|society
Old-growth survey grid centroid|location
Old-growth forest|environment
Commercial|economy

The above is the mapping of these non-existent ANZLIC search words to ISO Topic Categories that has been added to the Metashare metartool.

**Comment by sppigot** [comment]
My dump of the metashare database doesn't seem to have a dataset with NAME = BUSHFIRE_SEVERITY_EAST_AND_NORTHEAST_VICTORIA_2019-20

**Comment by sppigot** [comment]
Closing the issue but the conversion might still spit out an error for the dataset with NAME = BUSHFIRE_SEVERITY_EAST_AND_NORTHEAST_VICTORIA_2019-20 - so reopen if that is still causing problems

**Comment by sppigot** [comment]
VIC_LANDCOVER_TS works fine from my dump

**Comment by sppigot** [comment]
...and thanks @milleri for providing the error dumps.
