### ISSUE TITLE
geonetwork metadata report- missing Resource Name and Access Contraint

### ISSUE THREAD

**Issue by tp0b** [geonetwork-delwp/core-geonetwork#16]
The vector geonetwork metadata report in html format (e.g.  for [TR_ROAD](https://dev-metashare.maps.vic.gov.au/geonetwork/srv/api/records/61f633ae-c18c-5967-a546-84ceb44273f6/formatters/sdm-html?root=html&output=html)):

1.	Missing the Resource Name e.g TR_ROAD and instead it’s using the Title name.
2.	Missing is the wording in the field Access Constraint: is Creative Commons Attribution 4.0 International licence, Copyright and Attribution, Terms of Use - http://creativecommons.org/licenses/by/4.0/

The Access Constraint needs to point to GeoNetwork Constraints eg screenshot 

CC licecne:-
![image](https://user-images.githubusercontent.com/64397239/95693186-c5d9ed80-0c76-11eb-9679-a48604d0d486.png)

Or DALA for Limited Classifications.

![image](https://user-images.githubusercontent.com/64397239/95693194-d0948280-0c76-11eb-9ee8-134fa83c9f7a.png)

**Comment by tp0b** [comment]
hi @milleri to update these two above items, can I do it in geonetwork admin console on the web or is this something you have to do at the backend? Thanks.

**Comment by svdeveloper1** [comment]
This requires modification to the XSL report format and redeployment, as per the email I just sent you.

**Comment by tp0b** [comment]
these fields are now in html report

![image](https://user-images.githubusercontent.com/64397239/174917755-9fc825f3-75c0-4c2b-b204-b000b14445e1.png)
