### ISSUE TITLE
add a new value for "Representation Type": View 

### ISSUE THREAD

**Issue by tp0b** [geonetwork-delwp/core-geonetwork#17]
Hi Ian and Tom, ESS is currently dicussing the need of distinguish between a vector and a view dataset/product so that when changes in view triggered by deleting or adding column(s )in table, we know which views the column belongs to. Under this design, each view is having a geonetwork record and relationship with dataset is set in geonetwork. 

We are wondering how easily is to add a new value of "Representative Type" of View into Geonetwork and what are required tasks need to be updated in related processes (e.g. metar harvesting) so that Geonetwork can be functioning as it is now. Thanks.

**Comment by svdeveloper1** [comment]
These are all coding tasks for Simon.
The current list of representationtypes is maintained in the DELWP specific area of the ISO19115-3 repo (https://github.com/geonetwork-delwp/iso19115-3.2018/blob/master/codelists.xml)
The mapping from Metashare to the representation types is done in metar, via the following file (https://github.com/geonetwork-delwp/metashare/blob/master/data/reftab__ms2ap_spatial_rep_type.txt) which maps Metashare object types to GeoNetwork representation types.

**Comment by tp0b** [comment]
editor can update spatialresprentation_text from Vector to View in GN DEV

**Comment by tp0b** [comment]
![image](https://user-images.githubusercontent.com/64397239/174916713-e75a6383-ade4-4500-b3f9-cb6a6838c1b4.png)
