### ISSUE TITLE
Full view-An error occured while loading a metadata view

### ISSUE THREAD

**Issue by tp0b** [geonetwork-delwp/core-geonetwork#19]
When I click on Display mode of geonetwork record, i have an error message

https://dev-metashare.maps.vic.gov.au/geonetwork/srv/eng/catalog.search#/metadata/8f3e3caa-e4bd-5e43-afc4-59b71c1f27f2

![image](https://user-images.githubusercontent.com/64397239/109259555-8d673480-7850-11eb-8ea6-b3679be98071.png)

**Comment by milleri** [comment]
My bad - I was testing changes to the citation link.  I have reverted this and it is working now.  BTW, I have the correct link displaying now (i.e. same as the permalink) but when clicked the link still doesn't go to this url.
