### ISSUE TITLE
The latest DEV instance Filters are inconsistant with UAT STG and PROD

### ISSUE THREAD

**Issue by spatialgeorge** [geonetwork-delwp/core-geonetwork#23]
The latest build of Geonetwork and the updated MetaR processes have changed the listing in the left hand side filters.

**Comment by spatialgeorge** [comment]
In the Type of Resource its missing Non Geographic datasets and products.
![image](https://user-images.githubusercontent.com/46309965/144936624-1d63f0d3-a5fb-4906-9bf7-49d68505ca2a.png)

Groups is also missing.
![image](https://user-images.githubusercontent.com/46309965/144937195-44c8be49-61c4-4f42-bdfa-efdb1e0da9f6.png)

**Comment by sppigot** [comment]
Added the group, the first is because of something else
