### ISSUE TITLE
Cannot edit 3D records 

### ISSUE THREAD

**Issue by spatialgeorge** [geonetwork-delwp/core-geonetwork#24]
Not sure why this is different, cannot edit a 3d record, example https://dev-metashare.maps.vic.gov.au/geonetwork/srv/eng/catalog.search#/metadata/ebf8e241-7cb0-5764-bb46-5f11bcd12f3c

Getting an error when calling service.

**Comment by sppigot** [comment]
This appears to be because the record is being selected as applicable for two views by the editor. I'll check and see why on my local version.

**Comment by sppigot** [comment]
George - the problem with the 3D records is that they are CIP projects but there is no acquisition information. The editor thinks that the record is a metashare record (no acquisition information) **and** a rastermeta project (scope code is project)

**Comment by sppigot** [comment]
Can you let me know what we should do to delineate these? Seems kind of odd that a rastermeta project has no acquisition info.

**Comment by spatialgeorge** [comment]
I had a very good look at UAT and DEV and both CIP projects and 3D projects do have acquisition info, and are editable apologies

**Comment by tp0b** [comment]
we can open Editing mode for the record above
![image](https://user-images.githubusercontent.com/64397239/174916904-8e68f24e-cd00-4851-a02a-2ed0f9cfaa75.png)

**Comment by spatialgeorge** [comment]
Resolved
