### ISSUE TITLE
A non admin user cannot edit 

### ISSUE THREAD

**Issue by spatialgeorge** [geonetwork-delwp/core-geonetwork#26]
As a non admin user, cannot add a new contact.  The dropdown for the contacts is not displaying information

**Comment by spatialgeorge** [comment]
Created a registered user username - Simon     Password - Simon123$  to test

**Comment by spatialgeorge** [comment]
![image](https://user-images.githubusercontent.com/46309965/167959794-17b7b219-9961-444b-8c45-1476706e2563.png)

**Comment by sppigot** [comment]
George - I suspect the fragments don't have the right permissions - should be easy to fix. I'll log in with the suppled account thanks.

**Comment by sppigot** [comment]
George account details don't seem to be working on either dev or uat, which instance would that be please?

**Comment by spatialgeorge** [comment]
sorry Simon, I may have mistyped something    username simon   password Metashare123$   for DEV

**Comment by sppigot** [comment]
George - thanks - I can get in now - you might need to make me an editor user though as I can't use the editor as a registered user

**Comment by spatialgeorge** [comment]
Sorry late reply Simon, changed your account to EDITOR

**Comment by spatialgeorge** [comment]
Hi Simon,
It looks like some of the contacts in the EDIT UI are coming through but not all.  I can't seem to locate some contacts, i.e. Robert Lane from DJPR, there's lots of contacts I can't see in the dropdown.

**Comment by tp0b** [comment]
Contact look up can be seen for editor role in GN DEV
https://dev-metashare.maps.vic.gov.au/geonetwork/srv/eng/catalog.edit#/metadata/18239?redirectUrl=catalog.search%23%2Fmetadata%2F226ada5a-8fb1-449a-8d1e-d3072f5b22c2&tab=resourceContacts
![image](https://user-images.githubusercontent.com/64397239/174914058-04175565-75e7-4e70-b0d0-fe18e47c455b.png)

**Comment by spatialgeorge** [comment]
Rectified

**Comment by sppigot** [comment]
George,

Yes can see the issue - can you give my account admin rights please? So I can check the permissions on the fragments....

Simon
________________________________
