### ISSUE TITLE
Missing Field in Edit

### ISSUE THREAD

**Issue by spatialgeorge** [geonetwork-delwp/core-geonetwork#9]
The record below has a field, 'credit'   In the edit UI, we cannot locate this field.

Dataset                 MOG2005_EG
Title                       Modelled old-growth forest in East Gippsland
UUID                     4297b8884d942c4184157978c59f32dd4429b5e7

This has been a common reply from custodians who have tested the edit UI

[credit.pdf](https://github.com/geonetwork-delwp/core-geonetwork/files/4823153/credit.pdf)

**Comment by sppigot** [comment]
Added for metashare records.

**Comment by spatialgeorge** [comment]
We cannot find the Credit field in the edit UI.

**Comment by milleri** [comment]
This change has not yet been deployed

**Comment by spatialgeorge** [comment]
Hi Simon,   The Credit field is visible through the edit UI for the records that contain the field.  For the records that don't have that field we cannot add it and it seems there is no place where we can add other fields to edit.
We should be able to add any field through the EDIT UI not only the Credit field.
See image attached
![edit_ui](https://user-images.githubusercontent.com/46309965/88348670-6bc13e80-cd91-11ea-9402-56f0a26e9ca3.jpg)

**Comment by spatialgeorge** [comment]
This will be put into stage 2 plan as this is key to having a editable application.

**Comment by tp0b** [comment]
hi @sppigot we discussed the geonetwork UI edit capability and found the following example demonstrate our needs, for every metadata element there is + to add/update value and X (when hovering around the metadata element) to remove the current metadata element 

Waterways Geomorphic Habitat ([ANZVI0803008672](https://dev-metashare.maps.vic.gov.au/geonetwork/srv/eng/catalog.search#/metadata/0780b676-700a-5f2a-b858-e6ab787e4068)

![image](https://user-images.githubusercontent.com/64397239/99321160-52547d00-28c1-11eb-8042-95f1cd1f35e2.png)

**Comment by tp0b** [comment]
as an editor I can add Credit in Description tab in GN DEV

![image](https://user-images.githubusercontent.com/64397239/174917939-459596c3-a02d-41a4-ba3d-7c6132511522.png)
